dist: trusty

language: java

jdk:
  - openjdk12

cache:
  directories:
    - $HOME/.m2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - google-chrome-stable --remote-debugging-port=9222 http://localhost &

install:
  - mvn clean install -Dmaven.javadoc.skip=true -B -V

notifications:
  slack: evoco:HMLAFFFsZHDFu6xBw0OyXZrp